apiVersion: v1
kind: Pod
metadata:
  labels:
    app: foundryvtt
  name: foundryvtt
spec:
  containers:
  - name: foundry
    image: docker.io/felddy/foundryvtt:latest
    args:
    - resources/app/main.mjs
    - --port=30000
    - --headless
    - --noupdate
    - --dataPath=/data
    envFrom:
      - configMapRef:
          name: secrets
    env:
    - name: FOUNDRY_MINIFY_STATIC_FILES
      value: true
    - name: FOUNDRY_PROXY_PORT
      value: 443
    - name: FOUNDRY_PROXY_SSL
      value: true
    ports:
    - containerPort: 30000
      hostPort: 30000
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /home/foundry/foundrydata
      type: Directory
